### ISSUE TITLE
Legacy templates need to extend generic/object_detail.html

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot-plugin-device-lifecycle-mgmt#129]
All the detail templates in this plugin should be updated to extend `generic/object_detail.html` list templates are fine in this one.

**Comment by jvanderaa** [comment]
@HanlinMiao / @bryanculver can you provide some more detail on this issue? I'm not familiar enough to make a judgment call from this from just this bit of information rather than the base.html.

**Comment by glennmatthews** [comment]
Basically just a matter of using the correct template for object detail views. `object_detail.html` has been the recommended base template for these views since Nautobot 1.2.0. Using it instead of `base.html` provides at a minimum the following benefits:

1. Reduced need for apps to provide boilerplate template content (simpler templates in the app)
2. Easier/more automatic implementation of new features added to `object_detail.html` in later releases of Nautobot core that the app would need to implement for itself if using `base.html` instead.
